USER_NAME = "Example"
USER_NUMBER = "12345678"
CITY = "New York"

# Features
MORNING_GREETING = True
CLOSING_MESSAGE = True
DOG_PIC = True
RAIN_ALERT = True
HOLIDAY_ALERT = True
NBA_SCHEDULE = True
MOTIVATIONAL_QUOTE = True
